# Site settings
author: Shawn Sobieski
title: Learn, Create, Repeat
header-img: img/home-bg.png
email: shsobieski@gmail.com
copyright_name: Shawn Sobieski
description: > # this means to ignore newlines until "baseurl:"
  "Curiosity is the engine of achievement." - Sir Ken Robinson 
baseurl: "" # the subpath of your site, e.g. /blog
twitter_username: 
github_username:  shsobieski

# Build settings
markdown: kramdown
highlighter: rouge
permalink: pretty
paginate: 5
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]

gems: [jekyll-paginate, jekyll-feed]
